### PR TITLE
Purge pua

### PR DESCRIPTION
**Pull request by typiconman**
If there are no further changes to be made at this stage, I'd like to merge this in.

### CODE REVIEW

**Comment by starover77** [comment]
I would like an opportunity to look over the kerning pairs this evening when I get home from work. There are some pairs that obviously need some adjustment, and I want to check for duplicates between the Oldstyle and Newstyle sets. If you want to upload the current (today's) version, I suppose that's OK, but I would rather have an opportunity to make these adjustments first.

**Comment by typiconman** [comment]
Ok. That's fine. Keep pushing your changes to purge-pua.

**Comment by typiconman** [comment]
There still seem to be some problems with kerning, but I'll go ahead and merge this in now. Then we'll worry about the kerning.
test

**Comment by typiconman** [comment]
Merged and closed.

**Pull request merged**
